<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:data="urn:lut">
  <xsl:output method="text" />

  <xsl:template match="Category">
    <xsl:text>  { name: '</xsl:text><xsl:value-of select="@name" /><xsl:text>', characters: [&#13;</xsl:text>

    <xsl:apply-templates select="Entity" />

    <xsl:text>  ]}</xsl:text>
    <xsl:if test="following-sibling::Category[1]">
      <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:text>&#13;</xsl:text>
  </xsl:template>

  <xsl:template match="Entity">
    <xsl:text>    { codepoint: '</xsl:text>
    <xsl:value-of select="@codePoint" />
    <xsl:text>', text: '</xsl:text>
    <xsl:value-of select="@displayName" />
    <xsl:text>' }</xsl:text>

    <xsl:if test="following-sibling::Entity[1]">
      <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:text>&#13;</xsl:text>
  </xsl:template>

  <xsl:template match="/EntityList">
    <xsl:text>// this code generated by running generate-data-js.xslt on entities.xml&#13;</xsl:text>
    <xsl:text>var data = [&#13;</xsl:text>
    <xsl:apply-templates select="Category" />
    <xsl:text>]</xsl:text>
  </xsl:template>

</xsl:stylesheet>
