<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:data="urn:lut">
  <xsl:output method="text" />

  <xsl:template match="IconFont">
    <xsl:text>  { </xsl:text>

    <xsl:text>name: '</xsl:text><xsl:value-of select="@name" /><xsl:text>', </xsl:text>
    <xsl:text>size: </xsl:text><xsl:value-of select="@number" /><xsl:text>, </xsl:text>
    <xsl:text>width: </xsl:text><xsl:value-of select="@width" /><xsl:text>, </xsl:text>
    <xsl:text>height: </xsl:text><xsl:value-of select="@height" />

    <xsl:text>  }</xsl:text>

    <xsl:if test="following-sibling::IconFont[1]">
      <xsl:text>,</xsl:text>
    </xsl:if>
    <xsl:text>&#13;</xsl:text>
  </xsl:template>

  <xsl:template match="/IconFontList">
    <xsl:text>// this code generated by running generate-icon-data-js.xslt on fonticons.xml&#13;</xsl:text>
    <xsl:text>var data = [&#13;</xsl:text>
    <xsl:apply-templates select="IconFont" />
    <xsl:text>]</xsl:text>
  </xsl:template>

</xsl:stylesheet>
